[program:tabua-mare-api-3330]
command=/app/TabuaMareAPI 3330
directory=/app
autostart=true
autorestart=true
startsecs=3
stopsignal=TERM
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:tabua-mare-api-3340]
command=/app/TabuaMareAPI 3340
directory=/app
autostart=true
autorestart=true
startsecs=3
stopsignal=TERM
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startsecs=3
stopsignal=QUIT
priority=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
